services:
  - type: web
    name: qualityinspec
    env: python
    buildCommand: bash build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DB_SERVER
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
